/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lms;

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
/**
 *
 * @author toshipa
 */
public class login extends javax.swing.JFrame {
    
    String host;
    Connection con;
    String SQL;
    Statement stmt;
    ResultSet rs ;
   
    public login() {
        initComponents();
        this.setVisible(true);
        
         try{
             con =DriverManager.getConnection("jdbc:mysql://localhost:3306/system","root","root"); 
         }
                       
        catch(Exception e)
        {
           System.out.print(e.getMessage());
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jPanel1.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/l.png"))); // NOI18N
        jButton1.setText("Login  ");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");

        tf1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        tf2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(10, 0, 317, 330);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lms/b.jpg"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 350, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String enterd_email = "";
        String enterd_password = "";
        user a = null;
        jLabel3.setText("");
        try
        { 
            enterd_email = tf1.getText();
            enterd_password = tf2.getText();
            
            if(verify_admin(enterd_email,enterd_password))
            {
                System.out.println("admin");
                adminhome f = new adminhome();
                setVisible(false);  
                f.setVisible(true);
            }
            else if(verify_student(enterd_email,enterd_password))
            {       System.out.println("student");
                    a=getStudentData(enterd_email);
                    studenthome f = new studenthome(a);
                    
                    f.setVisible(true);
                    setVisible(false); 
            }
            else if(verify_teacher(enterd_email,enterd_password))
            {       System.out.println("teacher");
                    a=getTeacherData(enterd_email);
                    teacherhome f = new teacherhome(a);
                    f.setVisible(true);
                    setVisible(false); 
            }
            else
            {
                jLabel3.setText("Incorrect Password");
            }
                
        }
        catch(Exception e)
        {
            System.out.println("error login");
           System.out.print(e.toString());

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    boolean verify_admin(String enterd_email,String enterd_password){
        return enterd_email.equals("root") && enterd_password.equals("root");
    }
    boolean verify_student(String enterd_email,String enterd_password){
        try{
        PreparedStatement stmt=con.prepareStatement("select * from student WHERE email=?");
        stmt.setString(1,enterd_email);  
        ResultSet rs=stmt.executeQuery();  
        while(rs.next()){  
            return enterd_password.equals(rs.getString(3));
            }
        }
        catch(Exception e)
        { System.out.println(e.getMessage());  }
        return false;
    }
    boolean verify_teacher(String enterd_email,String enterd_password){
        try{
        PreparedStatement stmt=con.prepareStatement("select * from teacher WHERE email=?");
        stmt.setString(1,enterd_email);  
        ResultSet rs=stmt.executeQuery();  
        while(rs.next()){  
            return enterd_password.equals(rs.getString("password"));
            }
        }
        catch(Exception e)
        {System.out.println("error get password");
            System.out.println(e.getMessage());  }
        return false;
    }
    user getTeacherData(String enterd_email){
        
        try{
        PreparedStatement stmt=con.prepareStatement("select * from teacher WHERE email=?");
        stmt.setString(1,enterd_email);  
        ResultSet rs=stmt.executeQuery();  
        
        while(rs.next()){  
            user t_data=new user(rs.getInt("teacher_id"),rs.getString("name"),rs.getString("email"),"teacher", rs.getString("password"));
            return t_data;
            }
        
        
        }
        catch(Exception e)
        { System.out.println(e.toString()); 
        
        }
        return null;
    }
    user getStudentData(String enterd_email){
        
        try{
        PreparedStatement stmt=con.prepareStatement("select * from student WHERE email=?");
        stmt.setString(1,enterd_email);  
        ResultSet rs=stmt.executeQuery();  
        
        while(rs.next()){  
            user s_data=new user(rs.getInt("student_id"),rs.getString("name"),rs.getString("email"),"student", rs.getString("password"));
            return s_data;}
        }
        catch(Exception e){ System.out.println(e.toString());         }
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
